// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

// ---------- CV Download Link ----------
export const CV_DOWNLOAD = "/cv/CV-Luis-Miguel-Palacios.pdf";
export const CV_FILENAME = "CV-Luis-Miguel-Palacios.pdf";

// ---------- Themes ----------
// Debe coincidir con los temas definidos en tailwind.config.mjs.
// "dark" indica si el tema es oscuro (aplica la clase "dark" para los estilos dark: de Tailwind).
export const THEMES = [
  { name: "fantasy", label: "Fantasy", dark: false },
  { name: "retro", label: "Retro", dark: false },
  { name: "corporate", label: "Corporate", dark: false },
  { name: "aqua", label: "Aqua", dark: false },
  { name: "dark", label: "Dark", dark: true },
  { name: "synthwave", label: "Synthwave", dark: false },
  { name: "black", label: "Black", dark: true },
  { name: "night", label: "Night", dark: true },
  { name: "dracula", label: "Dracula", dark: true },
];
export const DEFAULT_THEME = "fantasy";

// ---------- Menu Items ----------
export const MENU_ITEMS = [
  {
    title: "Perfil",
    tooltip: "left",
    url: "/profile",
    icon: "lucide:user-round",
  },
  {
    title: "Experiencia",
    tooltip: "bottom",
    url: "/experience",
    icon: "lucide:briefcase",
  },
  {
    title: "Proyectos",
    tooltip: "bottom",
    url: "/projects",
    icon: "lucide:folder-git-2",
  },
  {
    title: "Blog",
    tooltip: "bottom",
    url: "/blog",
    icon: "lucide:newspaper",
  },
  {
    title: "Contacto",
    tooltip: "right",
    url: "/contact",
    icon: "lucide:mail",
  },
];

// ---------- Icons Tech Stack  ----------
// `icon` es el nombre completo para astro-icon:
//   - "simple-icons:<slug>" para logos de marca (Simple Icons)
//   - "tech_skills/<name>" para SVG locales cuando Simple Icons no tiene el logo
// `icon` es el nombre para astro-icon:
//   - "simple-icons:<slug>" para logos de marca (Simple Icons)
//   - "tech_skills/<name>" para SVG locales cuando Simple Icons no tiene el logo
//   - "" (vacio) para chips de solo texto (conceptos, o marcas sin logo en Simple Icons)
export const TECH_STACK = [
  // Lenguajes
  { category: "Lenguajes", icon: "simple-icons:openjdk", name: "Java" },
  { category: "Lenguajes", icon: "simple-icons:csharp", name: "C#" },
  { category: "Lenguajes", icon: "simple-icons:javascript", name: "JavaScript" },
  { category: "Lenguajes", icon: "simple-icons:typescript", name: "TypeScript" },
  { category: "Lenguajes", icon: "simple-icons:python", name: "Python" },
  { category: "Lenguajes", icon: "simple-icons:html5", name: "HTML" },
  { category: "Lenguajes", icon: "simple-icons:css3", name: "CSS" },

  // Back-end & Frameworks
  { category: "Back-end & Frameworks", icon: "simple-icons:quarkus", name: "Quarkus" },
  { category: "Back-end & Frameworks", icon: "simple-icons:spring", name: "Spring Boot" },
  { category: "Back-end & Frameworks", icon: "simple-icons:dotnet", name: ".NET" },
  { category: "Back-end & Frameworks", icon: "", name: ".NET Framework" },
  { category: "Back-end & Frameworks", icon: "simple-icons:django", name: "Django" },
  { category: "Back-end & Frameworks", icon: "", name: "Microservicios" },

  // Front-end
  { category: "Front-end", icon: "simple-icons:react", name: "React" },
  { category: "Front-end", icon: "simple-icons:angular", name: "Angular" },
  { category: "Front-end", icon: "simple-icons:astro", name: "Astro" },
  { category: "Front-end", icon: "simple-icons:tailwindcss", name: "Tailwind" },

  // Bases de datos
  { category: "Bases de datos", icon: "simple-icons:microsoftsqlserver", name: "SQL Server" },
  { category: "Bases de datos", icon: "simple-icons:oracle", name: "Oracle" },
  { category: "Bases de datos", icon: "simple-icons:postgresql", name: "PostgreSQL" },
  { category: "Bases de datos", icon: "simple-icons:mysql", name: "MySQL" },
  { category: "Bases de datos", icon: "simple-icons:sqlite", name: "SQLite" },
  { category: "Bases de datos", icon: "simple-icons:mongodb", name: "MongoDB" },

  // DevOps & Testing
  { category: "DevOps & Testing", icon: "simple-icons:amazonwebservices", name: "AWS" },
  { category: "DevOps & Testing", icon: "simple-icons:docker", name: "Docker" },
  { category: "DevOps & Testing", icon: "simple-icons:redhatopenshift", name: "OpenShift" },
  { category: "DevOps & Testing", icon: "simple-icons:sonarqube", name: "SonarQube" },
  { category: "DevOps & Testing", icon: "simple-icons:apachejmeter", name: "JMeter" },
  { category: "DevOps & Testing", icon: "simple-icons:junit5", name: "JUnit" },
  { category: "DevOps & Testing", icon: "", name: "NUnit" },
  { category: "DevOps & Testing", icon: "simple-icons:git", name: "Git" },
  { category: "DevOps & Testing", icon: "simple-icons:gitlab", name: "GitLab" },
  { category: "DevOps & Testing", icon: "simple-icons:github", name: "GitHub" },

  // Medios de pago
  { category: "Medios de pago", icon: "simple-icons:visa", name: "Visa" },
  { category: "Medios de pago", icon: "simple-icons:mastercard", name: "Mastercard" },
  { category: "Medios de pago", icon: "", name: "ISO 8583" },
  { category: "Medios de pago", icon: "", name: "EMV / EMVco" },
  { category: "Medios de pago", icon: "", name: "3DS" },
  { category: "Medios de pago", icon: "", name: "Tokenización" },
  { category: "Medios de pago", icon: "", name: "HSM" },
  { category: "Medios de pago", icon: "", name: "Facilitador de Pagos" },
  { category: "Medios de pago", icon: "", name: "ATM" },
  { category: "Medios de pago", icon: "", name: "POS" },

  // Low-Code
  { category: "Low-Code", icon: "tech_skills/outsystems", name: "OutSystems" },

  // IA & Herramientas
  { category: "IA & Herramientas", icon: "simple-icons:claude", name: "Claude" },
  { category: "IA & Herramientas", icon: "simple-icons:claude", name: "Claude Code" },
  { category: "IA & Herramientas", icon: "simple-icons:openai", name: "ChatGPT" },
  { category: "IA & Herramientas", icon: "simple-icons:openai", name: "Codex" },
  { category: "IA & Herramientas", icon: "simple-icons:googlegemini", name: "Gemini" },
  { category: "IA & Herramientas", icon: "tech_skills/kiro", name: "Kiro" },
];

// ---------- Education  ----------
export const EDUCATIONS = [
  {
    educational_center: "AWS Community Day Ecuador",
    specialty: "Certificado de Participación AWS Community Day Ecuador 2026",
    date: "Septiembre 2026",
    image: "/education/AWS-ecuador.webp",
    certificate: "/education/Certificado-de-participacion-en-AWS-Community-Day-Ecuador-2026.webp",
    country: "Ecuador",
    modality: "Presencial",
    type: "participate",
    url: "https://ec-central-1.console.awscommunity.ec/certificados/DSA5BDSSD0HE",
    priority: 2,
  },
  {
    educational_center: "Anthropic Education",
    specialty: "Introduction to Model Context Protocol (MCP)",
    date: "Julio 2026",
    image: "/education/anthropiclogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://verify.skilljar.com/c/3mn4zu42w3fs",
    priority: 2,
  },
  {
    educational_center: "Anthropic Education",
    specialty: "Certificate of completion: Claude 101",
    date: "Mayo 2026",
    image: "/education/anthropiclogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://verify.skilljar.com/c/58zncjhof6zx",
    priority: 2,
  },
  {
    educational_center: "Anthropic Education",
    specialty: "Claude Code in Action",
    date: "Abril 2026",
    image: "/education/anthropiclogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://verify.skilljar.com/c/2r3udwkfr4b3",
    priority: 2,
  },
  {
    educational_center: "Dev/Talles",
    specialty: "n8n + MCP: Automatización y agentes de IA inteligentes",
    date: "Abril 2026",
    image: "/education/devtalleslogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://cursos.devtalles.com/certificates/4q7ntpxpgt",
    priority: 2,
  },
  {
    educational_center: "Dev/Talles",
    specialty: "Docker - Guía práctica de uso para desarrolladores",
    date: "Enero 2026",
    image: "/education/devtalleslogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://cursos.devtalles.com/certificates/r6v66pcc2m",
    priority: 2,
  },
  {
    educational_center: "Dev/Talles",
    specialty: "Patrones de Diseño: Soluciones prácticas y eficientes",
    date: "Noviembre 2025",
    image: "/education/devtalleslogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://cursos.devtalles.com/certificates/2nd5hem711",
    priority: 2,
  },
  {
    educational_center: "Universidad Internacional de la Rioja",
    specialty: "Maestría en Ingeniería de Software y Sistemas Informáticos",
    date: "Noviembre 30 2023",
    image: "/education/unir.webp",
    certificate: "/education/maestria.webp",
    country: "España",
    modality: "Online",
    type: "university",
    priority: 1,
  },
  {
    educational_center: "TÜV Rheinland Europe",
    specialty: "Internal Auditor ISO 27001:2022, Information Security Management Systems",
    date: "Noviembre 2023",
    image: "/education/treurope.webp",
    certificate: "/education/27001.webp",
    country: "",
    modality: "Online",
    type: "certification",
    url: "https://www.certipedia.com/quality_marks/0217523425?locale=es",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Diseña un sitio web con Bootstrap 5",
    date: "Marzo 2022",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/bootstrap",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Desarrollo personal",
    date: "Marzo 2022",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/desarrollo-personal",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Miro, la pizarra digital para trabajo remoto",
    date: "Febrero 2022",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/miro",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Variables CSS",
    date: "Diciembre 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/variables-css",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Copywriting: ¿cómo escribir para vender más?",
    date: "Mayo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/copywriting",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "CSS Avanzado",
    date: "Abril 2021",
    image: "/education/edteamlogo.png",
    certificate: "/education/certificado-curso-css.png",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/css-avanzado",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Equipos súper productivos con Notion",
    date: "Marzo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/notion-2021",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "¿Cómo crear infografías impactantes?",
    date: "Marzo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/infografias",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "App de Peliculas con Figma",
    date: "Marzo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/app-figma",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Figma desde cero",
    date: "Marzo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/figma-2019",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Flexbox y Grid",
    date: "Marzo 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/flexbox-grid",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Diseño UI",
    date: "Febrero 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/ui-design",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "Diseña tu propio flujo de trabajo en equipo con Git",
    date: "Enero 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/git-workflow",
    priority: 2,
  },
  {
    educational_center: "EDteam",
    specialty: "GIT desde cero",
    date: "Enero 2021",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/git-2019",
    priority: 2,
  },
  {
    educational_center: "CertiProf",
    specialty: "SDPC - Scrum Developer Professional Certificate",
    date: "Enero 2021",
    image: "/education/certiprof.webp",
    certificate: "/education/sdpc.webp",
    country: "",
    modality: "Online",
    type: "certification",
    priority: 1,
  },
  {
    educational_center: "EDteam",
    specialty: "Mi primera página web",
    date: "Diciembre 2020",
    image: "/education/edteamlogo.png",
    certificate: "",
    country: "",
    modality: "Online",
    type: "course",
    url: "https://ed.team/u/luismiguelpalaciosnugra/curso/pagina-web",
    priority: 2,
  },
  {
    educational_center: "Udemy",
    specialty: "Master en JavaScript",
    date: "Noviembre 2020",
    image: "/education/udemy.webp",
    certificate: "/education/masterjavascript.webp",
    country: "",
    modality: "Online",
    type: "course",
    priority: 1,
  },
  {
    educational_center: "CertiProf",
    specialty: "SFPC - Scrum Foundation Professional Certificate",
    date: "Julio 2020",
    image: "/education/certiprof.webp",
    certificate: "/education/sfpc.webp",
    country: "",
    modality: "Online",
    type: "certification",
    priority: 2,
  },
  {
    educational_center: "CertiProf",
    specialty: "SMPC - Scrum Master Professional Certificate",
    date: "Julio 2020",
    image: "/education/certiprof.webp",
    certificate: "/education/smpc.webp",
    country: "",
    modality: "Online",
    type: "certification",
    priority: 2,
  },
  {
    educational_center: "Universidad Católica de Cuenca",
    specialty: "Ingeniería de Sistemas",
    date: "Febrero 12 2020",
    image: "/education/ucacue.webp",
    certificate: "/education/ingsistemas.webp",
    country: "Ecuador",
    modality: "Presencial",
    type: "university",
    priority: 1,
  },
];

// ---------- Experience  ----------
export const EXPERIENCES = [
  {
    company: "Banco del Austro",
    job: "Arquitecto de Aplicaciones",
    tags: ["Actual", "Híbrido","Célula de Medios de Pago Procesamiento"],
    date: "Octubre 2025 - Actualidad",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/bdafavicon.ico",
    description:
      "Definición de arquitectura y modelado técnico de soluciones para el área de Medios de Pago, orientadas a la emisión de tarjetas, prevención de fraude y continuidad operativa, con foco en seguridad y buenas prácticas de desarrollo.",
    requirements: [
      "Definición e implementación de un kiosco de autoservicio para la emisión e impresión de tarjetas de débito innominadas, permitiendo a los clientes realizar el proceso de forma autónoma.",
      "Modelado técnico para la implementación de Safety Net de Mastercard en transacciones ON-US, orientado a la prevención de fraude en tiempo real.",
      "Optimización del flujo transaccional para Merchandise Return (MR) y Original Credit Transaction (OCT) con Visa, mejorando trazabilidad, control y consistencia.",
      "Participación en la implementación de un nuevo Issuer Master Key (IMK) para tarjetas Visa, asegurando la gestión criptográfica y la continuidad operativa.",
      "Definición de la solución técnica para migrar servicios internos hacia la nueva API de Equifax, garantizando integraciones seguras y desacopladas.",
      "Revisión técnica de Merge Requests, análisis de vulnerabilidades y acompañamiento en prácticas DevSecOps.",
    ],
    href: "ba-arquitecto",
    id: "ba-arquitecto",
  },
  {
    company: "Banco del Austro",
    job: "Ingeniero de Desarrollo Senior",
    tags: ["Presencial","Célula de Medios de Pago Adquirencia"],
    date: "Junio 2024 - Septiembre 2025 · 1 año 4 meses",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/bdafavicon.ico",
    description:
      "Desarrollo y certificación de soluciones de Medios de Pago con Visa y Mastercard: tokenización, EMV, 3DS y gestión criptográfica con HSM. Liderazgo técnico de la célula de Medios de Pago Adquirente.",
    requirements: [
      "Desarrollo y certificación con Visa y Mastercard de la tokenización de tarjetas (Card-on-File y comercio electrónico).",
      "Implementación de transacciones Money Send bajo mandato de Mastercard y del servicio de códigos de motivo de rechazo.",
      "Validación de transacciones con Visa Test System (VTS), Mastercard Authorization Simulator (MAS) y Mastercard Debit Financial Simulator (MDFS); certificación de POS Sunmi con SAVVI - FIME.",
      "Procesos de certificación EMV y manejo de PIN en transacciones con tarjeta chip; uso de HSM Atalla para la gestión criptográfica (CVV/CVC, iCVV, PIN, TRACK 2).",
      "Diseño y desarrollo de microservicios integrados con el core bancario Fitbank para el débito en cuenta y pago de deuda de tarjetas de crédito.",
      "Desarrollo e integración del switch transaccional con el facilitador de pagos Izipay (Perú) y de la afiliación de comercios con la API MATCH de Mastercard.",
      "Liderazgo técnico de la célula de Medios de Pago, acompañando a un equipo de 8 personas entre desarrolladores y QA.",
    ],
    href: "ba-senior",
    id: "ba-senior",
  },
  {
    company: "AustroRed",
    job: "Ingeniero de Desarrollo Senior",
    tags: ["Presencial"],
    date: "Mayo 2022 - Mayo 2024 · 2 años 1 mes",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/austrored.svg",
    description:
      "Desarrollo Back-end y Front-end de soluciones de Medios de Pago y aplicaciones bancarias, con microservicios en Java y Quarkus e implementación de mandatos de Visa y Mastercard sobre ISO 8583.",
    requirements: [
      "Implementación y mantenimiento de la aplicación de Tarjetas de Crédito (SysCard) en modalidad emisor, e integración de la pasarela de pagos Alignet.",
      "Desarrollo e integración de microservicios en Java, Quarkus, Docker y OpenShift; administración de bases de datos SQL Server (T-SQL).",
      "Soporte de BIN de 8 dígitos en el switch transaccional para ATM, POS, comercio electrónico, corresponsales no bancarios y cadenas corporativas.",
      "Migración del servidor Tokenizador de Windows Server 2019 a 2022 y mejora de microservicios de bloqueo/desbloqueo de tarjetas y comercios.",
      "Optimización del cobro de ISD mediante integración con el core de Tarjetas de Crédito y Débito, y actualización de tarifarios y estados de cuenta.",
    ],
    href: "austrored",
    id: "austrored",
  },
  {
    company: "Mastermoto",
    job: "Programador Senior",
    tags: ["Presencial"],
    date: "Enero 2022 - Mayo 2022 · 5 meses",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/mastermoto.png",
    description:
      "Desarrollo Back-end y Front-end de aplicaciones internas y web con Python, C# y Django, administración de bases de datos Oracle y soporte a la infraestructura tecnológica. ",
    requirements: [
      "Desarrollo del módulo de administración de marcaciones en la plataforma web con Python y Django.",
      "Prototipo de bot para Windows de envío masivo de mensajes de WhatsApp en campañas de cobranza, con Python y Selenium.",
      "Desarrollo y optimización de reportes operativos y de gestión con JasperReports.",
      "Administración de bases de datos Oracle (PL/SQL, Forms y Reports) y mejora de procesos de conciliación de transferencias bancarias.",
      "Mantenimiento de infraestructura en Linux y Windows, y gestión básica de seguridad (firewall, VPN).",
    ],
    href: "mastermoto",
    id: "mastermoto",
  },
  {
    company: "Banco del Austro",
    job: "Ingeniero de Desarrollo Junior",
    tags: ["Presencial"],
    date: "Agosto 2019 - Enero 2022 · 2 años 6 meses",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/bdafavicon.ico",
    description:
      "Desarrollo Back-end y Front-end de soluciones de tarjetas de crédito y banca virtual en sistemas transaccionales de alta criticidad, con integración a Visa y Mastercard bajo ISO 8583.",
    requirements: [
      "Desarrollo y mantenimiento de la aplicación SysCards en modalidad emisor e integración de la pasarela de pagos Alignet.",
      "Participación en el proyecto de integración de BIN de 8 dígitos con el proveedor TechSoft.",
      "Desarrollo de soluciones web para el refinanciamiento de tarjetas de crédito durante la pandemia de COVID-19.",
      "Servicios back-end para certificados digitales de tarjetas de crédito consumidos por la app móvil y funcionalidades de avances en efectivo desde la banca virtual.",
      "Actualización de criptografía CVN18 para tarjetas de crédito.",
      "Reportes regulatorios para la Superintendencia de Bancos e incorporación de información en el reporte AMMF (Acquirer Merchant Master File) de Visa.",
    ],
    href: "ba-junior",
    id: "ba-junior",
  },
  {
    company: "Consejo Nacional Electoral",
    job: "Operador de escáner",
    tags: ["Presencial"],
    date: "Marzo 2019 · 1 mes",
    city: "Cuenca",
    country: "Ecuador",
    logo: "/job_logos/cne.png",
    description:
      "Ejecución del proceso de transmisión de actas electorales, aplicando políticas de seguridad y apoyando en la verificación y reconteo de votos. Mi primera experiencia en entornos de alta responsabilidad y control operativo.",
    href: "cne",
    id: "cne",
  },
];

// ---------- Recognitions And Awards  ----------
export const RECOGNITIONSANDAWARDS = [
  {
    title:
      "Agente ágil del equipo Medios de Pago - Procesamiento",
    center: "Banco del Austro",
    expedition_date: "14 de abril de 2026",
    description:
      "Por haber sido elegido como AGENTE ÁGIL del equipo Medios de Pago - Procesamiento, en reconocimiento a su comunicación efectiva, actitud proactiva y apoyo constante al equipo. Su participación activa, recomendaciones para la mejora continua y confiabilidad fortalecen el desarrollo del trabajo colaborativo y la calidad de las entregas.",
    image: "/awards/reconocimiento-agente-agil.webp",
  },
  {
    title:
      "Mejor graduado de la Carrera de Ingeniería de Sistemas de la promosión 2020",
    center: "Universidad Católica de Cuenca",
    expedition_date: "12 de febrero de 2020",
    description:
      "La  Universidad  Católica  de  Cuenca,  y  Seguimiento  a  Graduados  me  ha  otorgado  el presente reconocimiento a la Excelencia y Mérito Académico por ser el mejor graduado de la Carrera de Ingeniería de Sistemas con un promedio 95 (Sobresaliente).",
    image: "/awards/mejorgraduado.webp",
  },
  {
    title:
      "2do lugar en el Salon  de  emprendimiento e  innovación en el año 2016",
    center: "Universidad Católica de Cuenca",
    expedition_date: "08 de diciembre de 2016",
    description:
      "Universidad Católica de Cuenca confiere el reconocimiento al proyecto: ALINPOL por haber obtenido el 2do. lugar en el SALON  DE  EMPRENDIMIENTO  E  INNOVACIÓN  2016, realizado en la Plaza del PORTAL REGIONAL DE ARTESANÍAS DE CUENCA-PRAC",
    image: "/awards/alinpol.webp",
  },
];

// ---------- Global Variables ----------
export const TRANSITION_API = true;
export const SITE_TITLE = "Portafolio de Luis Palacios ";
export const SITE_DESCRIPTION = "Portafolio web de Luis Miguel Palacios.";
export const GENERATE_SLUG_FROM_TITLE = true;
export const MYEMAIL = "palaciosluismig@gmail.com";